### ISSUE TITLE
GameChecker class

### ISSUE THREAD

**Issue by MajaPihl** [loghinfrancisc/Programming-MiniProject#19]
Create a class that:
- checks if the board is filled (add loop that checks through all of the board array values, and if any one of them is still null, return false. Otherwise, return true)
- checks if player has won by checking for the 8 possible win conditions (if the squares are taken)
- checks if a move is allowed (takes an int squarenumber and boolean currentplayer)

**Comment by MichalGrzymski9779** [comment]
nice work Maja! good u did it finally ;)
